import type { PropertySerialized, AgentSerialized } from '@/types'

export const MOCK_AGENTS: AgentSerialized[] = [
  {
    uid: 'agent-1',
    fullName: 'Sofia Martinez',
    email: 'sofia@raifi.co',
    phone: '3001234567',
    slug: 'sofia-martinez',
    avatarUrl: null,
    bio: 'Especialista en propiedades de inversion en el norte de Bogota. Mas de 8 anos ayudando a familias a encontrar su hogar ideal.',
    city: 'Bogota',
    department: 'Cundinamarca',
    specialties: ['inversion', 'vivienda'],
    yearsExperience: 8,
    dealsClosed: 45,
    isVerified: true,
    isOnboarded: true,
    isActive: true,
    whatsappNumber: '3001234567',
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    uid: 'agent-2',
    fullName: 'Carlos Restrepo',
    email: 'carlos@raifi.co',
    phone: '3109876543',
    slug: 'carlos-restrepo',
    avatarUrl: null,
    bio: 'Agente inmobiliario con amplia experiencia en el sector comercial y de oficinas en Medellin.',
    city: 'Medellin',
    department: 'Antioquia',
    specialties: ['comercial', 'inversion', 'arriendo'],
    yearsExperience: 12,
    dealsClosed: 78,
    isVerified: true,
    isOnboarded: true,
    isActive: true,
    whatsappNumber: '3109876543',
    createdAt: '2023-08-20T00:00:00Z',
    updatedAt: '2024-05-15T00:00:00Z',
  },
  {
    uid: 'agent-3',
    fullName: 'Valentina Ochoa',
    email: 'valentina@raifi.co',
    phone: '3205551234',
    slug: 'valentina-ochoa',
    avatarUrl: null,
    bio: 'Apasionada por el mercado de vivienda en Cali. Ayudo a jovenes profesionales a dar el paso a su primer apartamento.',
    city: 'Cali',
    department: 'Valle del Cauca',
    specialties: ['vivienda', 'arriendo'],
    yearsExperience: 3,
    dealsClosed: 15,
    isVerified: false,
    isOnboarded: true,
    isActive: true,
    whatsappNumber: '3205551234',
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    uid: 'agent-4',
    fullName: 'Andres Gutierrez',
    email: 'andres@raifi.co',
    phone: '3157778899',
    slug: 'andres-gutierrez',
    avatarUrl: null,
    bio: 'Experto en fincas y lotes en el eje cafetero. Conozco cada rincon de Quindio, Risaralda y Caldas.',
    city: 'Pereira',
    department: 'Risaralda',
    specialties: ['finca', 'lote', 'inversion'],
    yearsExperience: 15,
    dealsClosed: 120,
    isVerified: true,
    isOnboarded: true,
    isActive: true,
    whatsappNumber: '3157778899',
    createdAt: '2023-05-10T00:00:00Z',
    updatedAt: '2024-04-20T00:00:00Z',
  },
]

export const MOCK_PROPERTIES: PropertySerialized[] = [
  {
    id: 'prop-1',
    agentId: 'agent-1',
    agentName: 'Sofia Martinez',
    agentAvatarUrl: null,
    title: 'Apartamento moderno en Chapinero Alto',
    description: 'Hermoso apartamento de 85m2 en el corazon de Chapinero Alto. Cuenta con 2 habitaciones amplias, 2 banos, cocina integral, zona de lavanderia y un parqueadero cubierto. Edificio con gimnasio, salon social y seguridad 24 horas. Excelente ubicacion cerca de centros comerciales, restaurantes y transporte publico.',
    operation: 'venta',
    type: 'apartamento',
    status: 'active',
    price: 420000000,
    bedrooms: 2,
    bathrooms: 2,
    areaM2: 85,
    garageSpaces: 1,
    city: 'Bogota',
    department: 'Cundinamarca',
    neighborhood: 'Chapinero Alto',
    address: 'Calle 63 # 7-20',
    latitude: null,
    longitude: null,
    images: [
      { id: 'img-1', storagePath: '', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80', displayOrder: 0, isCover: true },
      { id: 'img-2', storagePath: '', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80', displayOrder: 1, isCover: false },
      { id: 'img-3', storagePath: '', url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80', displayOrder: 2, isCover: false },
    ],
    isFeatured: true,
    isColegaje: true,
    colegajeCommissionSplit: 50,
    viewsCount: 234,
    createdAt: '2024-05-20T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'prop-2',
    agentId: 'agent-2',
    agentName: 'Carlos Restrepo',
    agentAvatarUrl: null,
    title: 'Casa campestre en El Retiro',
    description: 'Espectacular casa campestre de 350m2 en lote de 1200m2 en El Retiro, Antioquia. 4 habitaciones con bano privado, amplia sala con chimenea, cocina gourmet, terraza con vista panoramica a las montanas. Piscina privada, BBQ, zona verde y parqueadero para 3 vehiculos.',
    operation: 'venta',
    type: 'casa',
    status: 'active',
    price: 1250000000,
    bedrooms: 4,
    bathrooms: 4,
    areaM2: 350,
    garageSpaces: 3,
    city: 'Medellin',
    department: 'Antioquia',
    neighborhood: 'El Retiro',
    address: 'Vereda Pantanillo',
    latitude: null,
    longitude: null,
    images: [
      { id: 'img-4', storagePath: '', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80', displayOrder: 0, isCover: true },
      { id: 'img-5', storagePath: '', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80', displayOrder: 1, isCover: false },
    ],
    isFeatured: true,
    isColegaje: false,
    colegajeCommissionSplit: 50,
    viewsCount: 567,
    createdAt: '2024-04-10T00:00:00Z',
    updatedAt: '2024-05-28T00:00:00Z',
  },
  {
    id: 'prop-3',
    agentId: 'agent-3',
    agentName: 'Valentina Ochoa',
    agentAvatarUrl: null,
    title: 'Apartaestudio en Ciudad Jardin',
    description: 'Acogedor apartaestudio de 42m2 ideal para profesionales jovenes o estudiantes. Completamente remodelado con acabados modernos, cocina americana, bano con ducha tipo lluvia. Edificio con porteria 24h, cerca de universidades y zona gastro de Ciudad Jardin.',
    operation: 'arriendo',
    type: 'apartaestudio',
    status: 'active',
    price: 1800000,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 42,
    garageSpaces: 0,
    city: 'Cali',
    department: 'Valle del Cauca',
    neighborhood: 'Ciudad Jardin',
    address: 'Calle 16 # 100-50',
    latitude: null,
    longitude: null,
    images: [
      { id: 'img-6', storagePath: '', url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80', displayOrder: 0, isCover: true },
    ],
    isFeatured: false,
    isColegaje: true,
    colegajeCommissionSplit: 50,
    viewsCount: 89,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'prop-4',
    agentId: 'agent-4',
    agentName: 'Andres Gutierrez',
    agentAvatarUrl: null,
    title: 'Finca cafetera en Quindio',
    description: 'Hermosa finca cafetera de 5 hectareas en el corazon del eje cafetero. Casa principal de 200m2 con 3 habitaciones, casa de huespedes, beneficiadero, secadero solar. 3 hectareas en produccion de cafe especial variedad Castillo. Vista espectacular al Valle del Cocora.',
    operation: 'venta',
    type: 'finca',
    status: 'active',
    price: 850000000,
    bedrooms: 3,
    bathrooms: 2,
    areaM2: 50000,
    garageSpaces: 2,
    city: 'Armenia',
    department: 'Quindio',
    neighborhood: 'Salento',
    address: 'Vereda Cocora',
    latitude: null,
    longitude: null,
    images: [
      { id: 'img-7', storagePath: '', url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80', displayOrder: 0, isCover: true },
      { id: 'img-8', storagePath: '', url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80', displayOrder: 1, isCover: false },
    ],
    isFeatured: true,
    isColegaje: true,
    colegajeCommissionSplit: 40,
    viewsCount: 412,
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2024-05-30T00:00:00Z',
  },
  {
    id: 'prop-5',
    agentId: 'agent-1',
    agentName: 'Sofia Martinez',
    agentAvatarUrl: null,
    title: 'Oficina premium en World Trade Center',
    description: 'Oficina de 120m2 en piso alto del World Trade Center Bogota. Planta libre, piso en porcelanato, cielo raso en drywall con iluminacion LED. 2 banos, cocineta, cableado estructurado. Vista panoramica a los cerros orientales.',
    operation: 'arriendo',
    type: 'oficina',
    status: 'active',
    price: 8500000,
    bedrooms: 0,
    bathrooms: 2,
    areaM2: 120,
    garageSpaces: 2,
    city: 'Bogota',
    department: 'Cundinamarca',
    neighborhood: 'Centro Internacional',
    address: 'Calle 100 # 8A-55',
    latitude: null,
    longitude: null,
    images: [
      { id: 'img-9', storagePath: '', url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80', displayOrder: 0, isCover: true },
    ],
    isFeatured: false,
    isColegaje: false,
    colegajeCommissionSplit: 50,
    viewsCount: 156,
    createdAt: '2024-05-25T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'prop-6',
    agentId: 'agent-2',
    agentName: 'Carlos Restrepo',
    agentAvatarUrl: null,
    title: 'Local comercial en El Poblado',
    description: 'Local comercial de 95m2 en zona premium de El Poblado, sobre via principal con alto flujo peatonal. Ideal para restaurante, tienda de ropa o showroom. Fachada en vidrio, aire acondicionado central, 2 banos.',
    operation: 'arriendo',
    type: 'local_comercial',
    status: 'active',
    price: 12000000,
    bedrooms: 0,
    bathrooms: 2,
    areaM2: 95,
    garageSpaces: 0,
    city: 'Medellin',
    department: 'Antioquia',
    neighborhood: 'El Poblado',
    address: 'Carrera 43A # 7-50',
    latitude: null,
    longitude: null,
    images: [
      { id: 'img-10', storagePath: '', url: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=800&q=80', displayOrder: 0, isCover: true },
    ],
    isFeatured: false,
    isColegaje: true,
    colegajeCommissionSplit: 50,
    viewsCount: 203,
    createdAt: '2024-05-18T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
]

export function getMockAgent(slugOrUid: string) {
  return MOCK_AGENTS.find((a) => a.slug === slugOrUid || a.uid === slugOrUid) || null
}

export function getMockProperty(id: string) {
  return MOCK_PROPERTIES.find((p) => p.id === id) || null
}

export function getMockPropertiesByAgent(agentId: string) {
  return MOCK_PROPERTIES.filter((p) => p.agentId === agentId && p.status === 'active')
}
